##############################################################################################################
# Derived from https://github.com/wurstmeister/storm-docker and https://github.com/wurstmeister/kafka-docker
# Apache 2.0 License
# Purpose: To deploy a Storm-Kafka-Zookeeper in docker
# 
# Steps:
# 1. Download and install Docker 1.12 or higher
# 2. cd to the directory of this file
# 3. docker-compose up -d
##############################################################################################################
version: '2'
services:
 mail:
    image: tvial/docker-mailserver:2.1
    hostname: mail
    container_name: mail
    domainname: srotya.local
    ports:
    - "25:25"
    - "143:143"
    - "587:587"
    - "993:993"
    environment:
    - ENABLE_SPAMASSASSIN=1
    - ENABLE_CLAMAV=1
    - ENABLE_FAIL2BAN=1
    - ONE_DIR=1
    - DMS_DEBUG=0
    cap_add:
    - NET_ADMIN
 nucleus:
    image: "ambuds/tau-nucleus:latest"
    ports:
      - "8080:8080"
    environment:
      MYSQL_ROOT_USERNAME: root
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_ADDRESS: mysqls:3306
      API_PORT: 9000
      API_HOST: api
      SMTP_SERVER: mail
    depends_on:
      - api
      - mail
 mysqls:
    image: mysql:5.7.12
    ports:
      - "53306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
 api:
    image: "ambuds/tau-api:latest"
    ports:
      - "9000:9000"
    environment:
      NUCLEUS_SERVER_URL: http://nucleus:8080
      MYSQL_HOST: mysqls
      MYSQL_PORT: 3306
      MYSQL_ADDRESS: mysqls:3306
      MYSQL_ROOT_USERNAME: root
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
    depends_on:
      - mysqls
    links:
      - mysqls
